# 1. What is a Python library? Why do we use Python libraries?

In [ ]:
A Python library is a collection of pre-written Python code that provides functionalities to perform specific tasks or solve particular problems. These libraries contain modules, classes, functions, and constants that can be imported and used in your Python programs.

Python libraries serve several purposes:

Reuse of Code: Libraries provide pre-written code for common tasks, allowing developers to reuse existing solutions rather than reinventing the wheel. This saves time and effort.

Increased Productivity: By using libraries, developers can focus on solving higher-level problems rather than spending time on low-level implementation details.

Specialized Functionality: Python libraries often offer specialized functionality for tasks such as data analysis, machine learning, web development, scientific computing, etc. These functionalities might require complex algorithms or data structures that are already implemented in the library.

Community Contribution: Python has a large and active community of developers who contribute to open-source libraries. These libraries are continuously updated, improved, and maintained by the community, providing a rich ecosystem for Python development.

Performance Optimization: Many Python libraries are written in languages like C or C++, which can offer better performance compared to pure Python implementations. By using these libraries, developers can leverage optimized code for performance-critical tasks.

# 2. What is the difference between Numpy array and List?

In [ ]:
NumPy arrays and Python lists are both used to store collections of data, but they have several differences:

Data Types:

In Python lists, elements can be of any data type, and different elements within the same list can have different types.
NumPy arrays, however, are homogeneous; all elements in a NumPy array must have the same data type. This allows for more efficient storage and operations on the data.
Memory Efficiency:

NumPy arrays are more memory efficient than Python lists. Because NumPy arrays are homogeneous, they require less memory overhead for storing metadata.
NumPy arrays also store data in a contiguous block of memory, which can improve cache locality and access speed compared to the scattered memory locations of Python lists.
Performance:

NumPy arrays generally offer better performance for numerical operations and computations compared to Python lists. NumPy's underlying implementation in C allows for optimized, vectorized operations that can be executed more efficiently than equivalent operations performed on Python lists using loops.
Functionality:

NumPy arrays provide a wide range of mathematical and array manipulation functions and methods, making them particularly useful for numerical computing, scientific computing, and data analysis tasks.
Python lists offer more flexibility and a broader range of built-in methods and functions compared to NumPy arrays, but they lack the specialized functionalities and optimizations for numerical computations that NumPy provides.
Ease of Use:

Python lists are generally easier to work with for simple data storage and manipulation tasks due to their flexibility and simplicity.
NumPy arrays require a bit more understanding of array-oriented programming concepts, but they offer powerful capabilities for numerical computing tasks once you become familiar with them.

# 3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2, 3, 4],
               [5, 6, 7, 8],
               [9, 10, 11, 12]])

In [4]:
arr.shape

(3, 4)

In [5]:
arr.size

12

In [7]:
arr.ndim

2

# 4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [8]:
df = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [9]:
first_row = df[0]

In [10]:
first_row

array([1, 2, 3, 4])

# 5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [3]:
import numpy as np
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])
df = arr[2,3]
df

12

# 6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3,4], [5,6,7,8],[9,10,11,12]])

In [6]:
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

# 7. How can you generate a random 3x3 matrix with values between 0 and 1?

In [7]:
random_matrix = np.random.rand(3, 3)

In [8]:
random_matrix

array([[0.09005555, 0.64951411, 0.44614108],
       [0.73945269, 0.77756845, 0.03359317],
       [0.8412952 , 0.15092223, 0.47995575]])

# 8. Describe the difference between np.random.rand and np.random.randn?

In [ ]:
- np.random.rand and np.random.randn are both functions provided by NumPy's random module for generating random numbers, but they have some key differences
- np.random.rand:
----------------------
Generates random numbers from a uniform distribution over [0, 1).
Takes dimensions of the desired output as arguments.
All values generated are equally likely.
It's suitable for creating arrays of random values uniformly distributed between 0 and 1.
Syntax: np.random.rand(d0, d1, ..., dn)
                                                           
- np.random.randn:
-----------------------

Generates random numbers from a standard normal distribution (mean=0, standard deviation=1).
Takes dimensions of the desired output as arguments.
Values are more likely to be near 0, following a bell-shaped curve.
Suitable for creating arrays of random values that follow a normal distribution.
Syntax: np.random.randn(d0, d1, ..., dn)                                                          

# 9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [9]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [12]:
arr[:, :, np.newaxis]

array([[[ 1],
        [ 2],
        [ 3],
        [ 4]],

       [[ 5],
        [ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11],
        [12]]])

# 10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

In [13]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

In [14]:
transposed_arr = np.transpose(arr)

In [15]:
transposed_arr

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# 11. Consider the following matrix:
# Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
# Perform the following operation using Python1
# 1. Index wise multiplication'
# 2. Matix multiplication'
# 3. Add both the matics
# 4. Subtact matix B  from A
# 5. Diide Matix B by A

In [16]:
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

In [17]:
B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# 1. Index wise multiplication'

In [18]:
index_wise_multiplication = A * B

In [19]:
index_wise_multiplication

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

# 2. Matrix multiplication

In [20]:
matrix_multiplication = np.matmul(A, B.T)

In [21]:
matrix_multiplication

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

# 3. Addition of both matrices

In [22]:
matrix_addition = A + B

In [23]:
matrix_addition

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

# 4. Subtraction of matrix B from matrix A

In [24]:
matrix_subtraction = A - B

In [25]:
matrix_subtraction

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# 5. Element-wise division of matrix B by matrix A

In [26]:
element_wise_division = np.divide(B, A)

In [27]:
element_wise_division

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be used to swap the byte order of an array?

In [33]:
arr = np.array([1, 2, 3, 4], dtype=np.int32)

In [34]:
swapped_arr = arr.byteswap()

In [35]:
swapped_arr

array([16777216, 33554432, 50331648, 67108864])

# 13. What is the significance of the np.linalg.inv function?

In [ ]:
- The np.linalg.inv() function in NumPy is used to compute the inverse of a square matrix. The significance of this function lies in various mathematical and computational applications, particularly in linear algebra and solving systems of linear equations.

Here are some key points regarding the significance of np.linalg.inv()
- Applications in Statistics and Optimization: In statistics, the inverse of a covariance matrix is often used in multivariate analysis and parameter estimation techniques like the ordinary least squares (OLS) method. In optimization algorithms, the inverse of the Hessian matrix plays a significant role in determining the direction of descent.

Computational Efficiency: While computing the inverse of a matrix can be computationally expensive, particularly for large matrices, the np.linalg.inv() function leverages optimized algorithms and libraries, making the computation more efficient compared to manual implementation

# 14. What does the np.reshape function do, and how is it used?

In [ ]:
- The np.reshape() function in NumPy is used to change the shape (dimensions) of an array while preserving its data. It does not change the underlying data; rather, it changes how the data is interpreted by the array's shape.

Here's what np.reshape() does and how it is used

- Changing Array Shape: The primary purpose of np.reshape() is to change the shape of an array. This means you can convert an array from one-dimensional to multi-dimensional or vice versa, or simply change the dimensions of a multi-dimensional array.

- Preserving Data: When you reshape an array using np.reshape(), the function tries to create a new view of the data with the specified shape without changing the data itself. This means the reshaped array shares the same underlying data buffer as the original array
- Common Applications:

Preparing data for specific operations or algorithms that require a certain shape of input data.
Flattening multi-dimensional arrays into one-dimensional arrays or vice versa.
Reshaping arrays to match input requirements for neural networks or other machine learning algorithms    


# 15. What is broadcasting in Numpy?

In [ ]:
- Broadcasting in NumPy refers to the ability of NumPy to perform arithmetic operations on arrays of different shapes and sizes. This allows you to perform operations even if the arrays do not have the same shape, as long as they meet certain compatibility rules. Broadcasting effectively extends smaller arrays to match the shape of larger arrays during arithmetic operations, eliminating the need for explicit looping over array elements.

The broadcasting rule in NumPy follows these steps:

Dimension Compatibility: NumPy compares the dimensions of the two arrays element-wise, starting from the trailing dimensions and working its way forward. It checks if the dimensions are equal or if one of the dimensions is 1. If both conditions are met or if one of the arrays has fewer dimensions than the other, broadcasting is possible.

Array Extension: If broadcasting is possible, NumPy automatically extends (or "broadcasts") the smaller array along the missing dimensions to match the shape of the larger array. This extension involves replicating the values along the broadcasted dimensions without actually creating multiple copies of the data in memory.

Element-wise Operation: Once the arrays have been broadcasted to the same shape, NumPy performs the element-wise operation (e.g., addition, subtraction, multiplication) as usual.
    